[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=bb270dcd-e274-48fc-ac4d-f9730669b3ff
Description=Æðµã3.0
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
For 3
	MoveTo 1159, 579
	Delay 55
	LeftClick 1
	MoveTo 665, 81
	Delay 16943
	LeftClick 1
Next